spring:
 logging:
  file: logs/dev_app.log
  pattern:
   console: "%d %-5level %logger : %msg%n"
   file: "%d %-5level [%thread] %logger : %msg%n"
  level:
   org.springframework.web: DEBUG
   com.stackroute.controllers: DEBUG
   org.hibernate: DEBUG
  data:
   mongodb:
    database: mongoboot
    port: 27017
    host: localhost
  application:
    name: movie
#    mongodb.host: 172.23.238.175
#    mongodb.port: 27017
#    mongodb.uri: mongodb://172.23.238.175/test
#    mongo.repositories.enabled: true
 
server:
 port: 8080